import {
  Box, Container, Heading,
  Text, Badge
} from "@chakra-ui/react"
import Head from "next/head";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Loja do zé - Status page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW={'7xl'} p={7} mt={20}>
        <Heading
          textAlign={"center"}
          fontWeight="semibold"
          textTransform="uppercase"
          letterSpacing="wider"
          mb={1}
        >
          Status site do zé
        </Heading>
        <Box bg="gray.700" mb={2} p={2}>
          <Box
            mt={7}
            mb={8}
            bg="red.400"
            p={3}
            justifyContent={{ base: 'center', lg: 'space-between' }}
            flexDirection={{ base: 'column', lg: 'row' }}
            rounded="lg" display="flex"
          >
            <Text fontWeight={"bold"}> Alguns sistemas estão passando por uma grande interrupção</Text>
            <Text>um minuto atrás</Text>
          </Box>
          <Box color="black" mt={3} bg="gray.400" p={3} rounded="lg" display="flex" justifyContent={"space-between"}>
            <Text>API</Text>
            <Badge bg={"blue.400"}>Problemas de desempenho</Badge>
          </Box>
          <Box color="black" mt={3} bg="gray.400" p={3} rounded="lg" display="flex" justifyContent={"space-between"}>
            <Text>CDN</Text>
            <Badge bg={"green.400"}>Operacional</Badge>
          </Box>
          <Box color="black" mt={3} bg="gray.400" p={3} rounded="lg" display="flex" justifyContent={"space-between"}>
            <Text>Processador de pagamento</Text>
            <Badge bg={"green.400"}>Operacional</Badge>
          </Box>
          <Box color="black" mt={3} bg="gray.400" p={3} rounded="lg" display="flex" justifyContent={"space-between"}>
            <Text>Website</Text>
            <Badge bg={"green.400"}>Operacional</Badge>
          </Box>

        </Box>
        <Box mb={3}>
          <Text>
            Ultimas alterações
          </Text>
          <Box color="black" mt={3} bg="gray.400" p={3} borderLeftWidth="16px" borderLeftColor="purple.500" padding="7px" borderRadius="4px" >
            <Box display="flex" justifyContent={"space-between"}>
              <Text>
                <strong>Autor: {process.env.VERCEL_GIT_COMMIT_AUTHOR_LOGIN}</strong>
              </Text>
              <Badge bg={"#2f5888"}>GITHUB</Badge>
            </Box>
            <Box>
              <Text>Ultimo commit: {process.env.VERCEL_GIT_COMMIT_MESSAGE}</Text>
              <Text>hash: {process.env.VERCEL_GIT_COMMIT_SHA}</Text>
            </Box>
          </Box>
        </Box>
        <Text>
          Incidentes
        </Text>
        <Box color="black" mt={3} bg="gray.400" p={3} borderLeftWidth="16px" borderLeftColor="purple.500" padding="7px" borderRadius="4px" >
          <Box display="flex" justifyContent={"space-between"}>
            <Text>
              <strong>06 DE MAIO DE 2023, 5h36</strong>
            </Text>
            <Badge bg={"#2f5888"}>Fechado</Badge>
          </Box>
          <Box>
            <Text>Nossos serviços podem estar temporariamente indisponíveis</Text>
          </Box>
        </Box>
      </Container>
    </>
  )
}