import {
  Heading,
  Text,
  Center,
  Button,
  Container,
  Stack,
  Flex,
  Img as Image,
  Box,
  IconProps,
  Icon,
  Link
} from '@chakra-ui/react';
import Head from 'next/head';
import NextLink from "next/link"
import Accordion from '@/component/Accordion';
import CardGrid from '@/component/CardGrid';
import { Ticker } from '@/component/Marquee';
import { AppStores } from '@/component/Bannner/AppStore';
import Stats from '@/component/StatsCount';
import Footer from '@/component/Footer';
import { FaSearchPlus, FaArrowDown } from 'react-icons/fa'
export default function Home() {
  return (
    <>
      <Head>
        <title>Loja do zé - Vende tudo!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW={'7xl'} id="intro">
        <Stack
          align={'center'}
          spacing={{ base: 8, md: 10 }}
          py={{ base: 20, md: 28 }}
          direction={{ base: 'column', lg: 'row' }}
        >
          <Stack flex={1} spacing={{ base: 5, md: 10 }} mb={3}>
            <Box maxW='32rem'>
              <Heading
                mb={4}
                lineHeight={1.1}
                fontWeight={600}
                fontSize={{ base: '3xl', sm: '4xl', }}
              >
                <Text
                  as={'span'}
                  position={'relative'}
                  _after={{
                    content: "''",
                    width: 'full',
                    height: '10%',
                    position: 'absolute',
                    bottom: 1,
                    left: 0,
                    bg: 'blue.400',
                    zIndex: -1,
                  }}>
                  Loja do Zé
                </Text>, onde você acha a maior variedade!
              </Heading>
              <Text fontSize='xl'>
                Aqui você econtra de tudo e um pouco. Oferecemos a maior variedade de produtos
              </Text>
              <NextLink href={"/home"}>
                <Button
                  bg='teal.600'
                  mt='24px'
                  rounded={'full'}
                  size={'lg'}
                  fontWeight={'normal'}
                  px={6}
                  color='white'
                  w="100%"
                  _hover={{
                    bg: 'teal.500'
                  }}
                  outline={'none'}
                  leftIcon={<FaSearchPlus />}
                >
                  Procurar produtos
                </Button>
              </NextLink>
            </Box>
          </Stack>
          <Flex
            flex={1}
            justify={'center'}
            align={'center'}
            w={'full'}
            position={'relative'}
          >
            <Blob
              mt={5}
              w={'100%'}
              h={'122%'}
              position={'absolute'}
              top={'-20%'}
              left={0}
              zIndex={-1}
              color='purple.300'
            />
            <Center>
              <Image
                alt={'Hero Image'}
                objectFit={'cover'}
                alignItems='center'
                w={'100%'}
                h={'100%'}
                loading="lazy"
                src={
                  'https://assets.website-files.com/6364b6fd26e298b11fb9391f/6364b6fd26e2983671b93d4b_drawkit-32%20(1).png'
                }
              />
            </Center>
          </Flex>
        </Stack>
        <Center>
          <Link href='#cardgrid' border={'2px solid #B794F4'} p={2} borderRadius={'full'}>
            <FaArrowDown size={22} />
          </Link>
        </Center>
      </Container>
      <Ticker />
      <CardGrid />
      <Stats />
      <AppStores />
      <Accordion />
      <Footer />
    </>
  );
}

export const Blob = (props: IconProps) => {
  return (
    <Icon
      width={'100%'}
      viewBox="0 0 578 440"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M239.184 439.443c-55.13-5.419-110.241-21.365-151.074-58.767C42.307 338.722-7.478 282.729.938 221.217c8.433-61.644 78.896-91.048 126.871-130.712 34.337-28.388 70.198-51.348 112.004-66.78C282.34 8.024 325.382-3.369 370.518.904c54.019 5.115 112.774 10.886 150.881 49.482 39.916 40.427 49.421 100.753 53.385 157.402 4.13 59.015 11.255 128.44-30.444 170.44-41.383 41.683-111.6 19.106-169.213 30.663-46.68 9.364-88.56 35.21-135.943 30.551z"
        fill="currentColor"
      />
    </Icon>
  );
};