export const produtosDestaque = [
  {
    id: 1,
    title: "Fone de Ouvido Sem Fio",
    price: 59.99,
    photo: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
    // rating: 4.5,
    // category: "Eletrônicos",
    description: "Desfrute da liberdade de ouvir música sem fios com este fone de ouvido de alta qualidade. Com tecnologia avançada de cancelamento de ruído e longa duração da bateria, você pode aproveitar sua música.",
  },
  {
    id: 2,
    title: "Smartphone",
    price: 899.99,
    photo: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
    // rating: 4.2,
    // category: "Eletrônicos",
    description: "Este smartphone possui um design elegante e recursos avançados. Com uma tela de alta definição, processador rápido e câmera de alta resolução, você pode desfrutar de um.",
  },
  {
    id: 3,
    title: "Camiseta Casual Masculina",
    price: 39.99,
    photo: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
    // rating: 4.0,
    // category: "Roupas",
    description: "Esta camiseta casual masculina é perfeita para o dia a dia. Feita com um tecido macio e confortável, ela oferece estilo e conforto ao mesmo tempo. Combine com jeans ou bermuda para um visual descontraído.",
  },
  {
    id: 4,
    title: "Bola de basquete",
    price: 39.99,
    photo: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
    // rating: 4.0,
    // category: "Roupas",
    description: "Esta camiseta casual masculina é perfeita para o dia a dia. Feita com um tecido macio e confortável, ela oferece estilo e conforto ao mesmo tempo. Combine com jeans ou bermuda para um visual descontraído.",
  },
  {
    id: 5,
    title: "Bolo de chocolate",
    price: 39.99,
    photo: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
    // rating: 4.0,
    // category: "Roupas",
    description: "Esta camiseta casual masculina é perfeita para o dia a dia. Feita com um tecido macio e confortável, ela oferece estilo e conforto ao mesmo tempo. Combine com jeans ou bermuda para um visual descontraído.",
  },
  {
    id: 6,
    title: "Maça",
    price: 39.99,
    photo: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
    // rating: 4.0,
    // category: "Roupas",
    description: "Esta camiseta casual masculina é perfeita para o dia a dia. Feita com um tecido macio e confortável, ela oferece estilo e conforto ao mesmo tempo. Combine com jeans ou bermuda para um visual descontraído.",
  },
];